### ISSUE TITLE
unstable behaviour of network tests on Windows CI checks (AppVeyor)

### ISSUE THREAD

**Issue by maqi** [maidsafe/safe_vault#250]
After two more network churn tests have been included in the CI as part of the PR (https://github.com/maidsafe/safe_vault/pull/248), it is observed windows CI checks having an unstable result for network tests.
Along the PR 248, there are a sequence of commits having no change to the code itself except the travis script, however the results from AppVeyor keeps changing:
1, commit baeaf46, AppVeyor build https://ci.appveyor.com/project/MaidSafe-QA/safe-vault/build/1.0.155
having succeeded on x86 but failed on x64
2, commit 470c576, AppVeyor buld https://ci.appveyor.com/project/MaidSafe-QA/safe-vault/build/1.0.156
having failed on x86, but succeeded on x64
3, commit 1f19d95, AppVeyor buld https://ci.appveyor.com/project/MaidSafe-QA/safe-vault/build/1.0.157
having failed on x86, but succeeded on x64
4, commit 8c320d7, AppVeyor buld https://ci.appveyor.com/project/MaidSafe-QA/safe-vault/build/1.0.158
having failed on x86, but succeeded on x64
5, commit 21653d2, AppVeyor buld https://ci.appveyor.com/project/MaidSafe-QA/safe-vault/build/1.0.162
both succeeded on x86 and x64

It has to be noted that there is a cancellation of vast number of queuing AppVeyor builds carried out between the build 158 and 162, which may be related to this issue or not.

It also worth to mention that when failure happens on x64, the error is:
network_churn_immutable_data_test starting new vault
thread 'ConnectionManager bootstrap loop' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: NotConnected, error: StringError("os error") }) }', ../src/libcore\result.rs:736
thread 'vault::test::network_churn_immutable_data_test' panicked at 'waiting_for_hits can't resolve within the expected duration', src\vault.rs:538

which indicates a failure in starting a new vault. But the failure on x86 is always can not fetch the expected data:
network_churn_immutable_data_test getting data
thread 'vault::test::network_churn_immutable_data_test' panicked at 'waiting_for_client_get can't resolve within the expected duration', src\vault.rs:557

**Comment by maqi** [comment]
while looking at the issue that network_churn tests having a noticable failing rate in travis::linux and appveyor::win ,  it is figured out the reason is un-controllable order of incoming event. Our current implementation of churn/refresh/account_transfer is based on the assumption that sequence of events happens like `churn->refresh_to_network->receiving_refresh(i.e. account_transfer)` . However, when a node joining the network, refreshing to network will be triggered earlier on some nodes than the others get connected to the new node. This cause the following order of events are possible : ` receiving_refresh(i.e. account_transfer) -> churn -> refresh_to_network`, which leaves the `slow node` losing some accounts. The slower performance of the machine running the test, the more `slow node` will have, once pass the threshold, the later on get request can not be handled as there won't be enough get request being forwarded from DM to PN to be accumulated and resolved. This explains why appveyor having a higher rate of failure than travis::linux.

**Comment by maqi** [comment]
one solution quick to be deployed is: instead of clean up all accounts in churn, vault still keeps those accounts. but once a refreshed account is in, the existing account shall be replaced by the incoming merged one. This is much like what is being used by routing example churn test.

this is being implemented in https://github.com/maidsafe/safe_vault/pull/252
