### ISSUE TITLE
vault::test::network_test is failing 

### ISSUE THREAD

**Issue by rossmuir** [maidsafe/safe_vault#312]
As part of PR > https://github.com/maidsafe/safe_vault/pull/311 which is to remove wildcard dependencies and fix a few minor issues - we have `safe_vault` building but now `vault::test::network_test` is  failing. 

```
$ cargo test --release -- --nocapture vault::test::network_test;

   Compiling safe_vault v0.2.1 (file:///home/travis/build/maidsafe/safe_vault)

     Running target/release/lib-409b2ed91a8a0a2a

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured

     Running target/release/safe_vault-56fc567ea033cd32

running 1 test

Starting vault 0

Starting vault 1

Starting vault 2

Starting vault 3

ERROR:routing::routing_node: ConnectResponse already connected to ManagedNode(name:1bc072..df25ed).

ERROR:routing::routing_node: ConnectResponse already connected to ManagedNode(name:2ac081..8a1358).

ERROR:routing::routing_node: ConnectResponse already connected to ManagedNode(name:13e72c..f71ffc).

Starting vault 4

thread 'vault::test::network_test' panicked at '

 ===================================================================================================

| Result evaluated to Err: "Failed to get 4 hits within the expected duration.  Only hit vaults []" |

 ===================================================================================================

', src/vault.rs:373

test vault::test::network_test ... FAILED

failures:

failures:

    vault::test::network_test

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured


```

**Comment by rossmuir** [comment]
Additional info from windows
```
running 1 test
test vault::test::network_test ...  
If this test hangs, stopping the process with ctrl+C will not suffice.
You should kill the process via the Task Manager, or by running:
  taskkill /f /fi "imagename eq safe_vault-*" /im *
 
Starting vault 0
Starting vault 1
Starting vault 2
Starting vault 3
ERROR:routing::routing_node: ConnectResponse already connected to ManagedNode(name:f0cede..0e680d).
 
ERROR:routing::routing_node: ConnectResponse already connected to ManagedNode(name:f0cede..0e680d).
 
Starting vault 4
thread 'vault::test::network_test' panicked at '
 
 ===================================================================================================
| Result evaluated to Err: "Failed to get 4 hits within the expected duration.  Only hit vaults []" |
 ===================================================================================================
 
', src\vault.rs:373
stack backtrace:
   0:           0x8495ba - <unknown>
   1:           0x851d8e - <unknown>
   2:           0x80ca6c - <unknown>
   3:           0x80d1db - <unknown>
   4:           0x47a75c - <unknown>
   5:           0x488b13 - <unknown>
   6:           0x4b3b88 - <unknown>
   7:           0x4b666d - <unknown>
   8:           0x839551 - <unknown>
   9:           0x4b6a4d - <unknown>
  10:           0x8503bd - <unknown>
  11:     0x7ffe052013d1 - <unknown>
FAILED 
 
failures:
 
failures:
    vault::test::network_test
 
test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured
 
thread 'Service::run loop' panicked at 'explicit panic', C:\Users\appveyor\.cargo\registry\src\github.com-0a35038f75765ae4\crust-0.5.1\src\service.rs:393
stack backtrace:
   0:           0x8495ba - <unknown>
   1:           0x851d8e - <unknown>
   2:           0x80ca6c - <unknown>
   3:           0x5dcb13 - <unknown>
   4:           0x618fd5 - <unknown>
   5:           0x5ee6d0 - <unknown>
   6:           0x839551 - <unknown>
   7:           0x5f05ba - <unknown>
   8:           0x8503bd - <unknown>
   9:     0x7ffe052013d1 - <unknown>
thread 'Service::run loop' panicked at 'explicit panic', C:\Users\appveyor\.cargo\registry\src\github.com-0a35038f75765ae4\crust-0.5.1\src\service.rs:393
stack backtrace:
   0:           0x8495ba - <unknown>
   1:           0x851d8e - <unknown>
   2:           0x80ca6c - <unknown>
   3:           0x5dcb13 - <unknown>
   4:           0x618fd5 - <unknown>
   5:           0x5ee6d0 - <unknown>
   6:           0x839551 - <unknown>
   7:           0x5f05ba - <unknown>
   8:           0x8503bd - <unknown>
   9:     0x7ffe052013d1 - <unknown>
thread 'Service::run loop' panicked at 'explicit panic', C:\Users\appveyor\.cargo\registry\src\github.com-0a35038f75765ae4\crust-0.5.1\src\service.rs:393
stack backtrace:
   0:           0x8495ba - <unknown>
   1:           0x851d8e - <unknown>
   2:           0x80ca6c - <unknown>
   3:           0x5dcb13 - <unknown>
   4:           0x618fd5 - <unknown>
   5:           0x5ee6d0 - <unknown>
   6:           0x839551 - <unknown>
   7:           0x5f05ba - <unknown>
   8:           0x8503bd - <unknown>
   9:     0x7ffe052013d1 - <unknown>
thread 'Service::run loop' panicked at 'explicit panic', C:\Users\appveyor\.cargo\registry\src\github.com-0a35038f75765ae4\crust-0.5.1\src\service.rs:393
stack backtrace:
   0:           0x8495ba - <unknown>
   1:           0x851d8e - <unknown>
   2:           0x80ca6c - <unknown>
   3:           0x5dcb13 - <unknown>
   4:           0x618fd5 - <unknown>
   5:           0x5ee6d0 - <unknown>
   6:           0x839551 - <unknown>
   7:           0x5f05ba - <unknown>
   8:           0x8503bd - <unknown>
   9:     0x7ffe052013d1 - <unknown>
thread 'Service::run loop' panicked at 'explicit panic', C:\Users\appveyor\.cargo\registry\src\github.com-0a35038f75765ae4\crust-0.5.1\src\service.rs:393
stack backtrace:
   0:           0x8495ba - <unknown>
   1:           0x851d8e - <unknown>
   2:           0x80ca6c - <unknown>
   3:           0x5dcb13 - <unknown>
   4:           0x618fd5 - <unknown>
   5:           0x5ee6d0 - <unknown>
   6:           0x839551 - <unknown>
   7:           0x5f05ba - <unknown>
   8:           0x8503bd - <unknown>
   9:     0x7ffe052013d1 - <unknown>
ERROR:routing::routing_core: Routing Node has disconnected. 
thread 'Vault 3 worker' panicked at 'Unable to start crust::Service Either the application has not called WSAStartup, or WSAStartup failed. (os error 10093)', C:\Users\appveyor\.cargo\registry\src\github.com-0a35038f75765ae4\routing-0.4.2\src\routing_node.rs:78 
stack backtrace:
   0:           0x8495ba - <unknown> 
   1:           0x851d8e - <unknown> 
   2:           0x80ca6c - <unknown> 
   3:           0x53948f - <unknown> 
   4:           0x52e8ab - <unknown> 
   5:           0x5b84c1 - <unknown> 
   6:           0x4595c5 - <unknown> 
   7:           0x47c098 - <unknown> 
   8:           0x839551 - <unknown> 
   9:           0x47c32a - <unknown> 
  10:           0x8503bd - <unknown> 
  11:     0x7ffe052013d1 - <unknown> 
ERROR:routing::routing_core: Routing Client has disconnected. 
 
Command exited with code 101
```

**Comment by maqi** [comment]
The failing test seems is due to the updates in crust/routing, when setting up the test network and there are more than 2 nodes ( say the third or forth nodes ) the previous established connection starts dropping among nodes.
So the test always failed as the setup of testing network is failed.

**Comment by Fraser999** [comment]
This test has been heavily refactored and is under active development, hence this issue is no longer valid.
