### ISSUE TITLE
Logic error on second vault instance

### ISSUE THREAD

**Issue by davidpbrown** [maidsafe/safe_vault#507]
Using @bluebird's community1-amd64-release vault, I started up two instances for no good reason other than to see if that could work well.. distinct folders for each of those. The first vault appeared to stay up - for a while but the network fragile and it did fail after 10mins.

The second instance crashed after only a couple of minutes with an error I've not seen before, and given that it suggests logic error, perhaps this below useful.

```
thread 'Crust PeerId(4ffc..) event loop' panicked at 'Logic Error', ../src/libcore/option.rs:700
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'Node thread' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', ../src/libcore/result.rs:746
thread 'Node thread' panicked at '

 ==============================
| Result evaluated to Err: Any |
 ==============================

', /home/travis/.cargo/registry/src/github.com-88ac128001ac3a9a/maidsafe_utilities-0.6.0/src/thread.rs:37
stack backtrace:
   1:           0x77c5a0 - std::sys::backtrace::tracing::imp::write::h4c73fcd3363076f5
   2:           0x78022b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h0422dbb3077e6747
   3:           0x77feb3 - std::panicking::default_hook::haac48fa641db8fa2
   4:           0x76b5bf - std::sys_common::unwind::begin_unwind_inner::h39d40f52add53ef7
   5:           0x76c858 - std::sys_common::unwind::begin_unwind_fmt::h64c0ff793199cc1b
   6:           0x5d5f7f - _<thread..RaiiThreadJoiner as std..ops..Drop>::drop::h2f72648cf85a5235
   7:           0x4ad812 - crust..Service::drop_contents.23336::hf90ae88ccf4b1bf8
   8:           0x4ad1ce - core..Core::drop.23331::hf9130c13607d9797
   9:           0x560225 - std::sys_common::unwind::try::try_fn::ha116764aacfa08c1
  10:           0x77b77b - __rust_try
  11:           0x77b70d - std::sys_common::unwind::inner_try::h9eebd8dc83f388a6
  12:           0x5603ea - _<F as std..boxed..FnBox<A>>::call_box::had2bfc8e3c719a1b
  13:           0x77ef34 - std::sys::thread::Thread::new::thread_start::h471ad90789353b5b
thread panicked while panicking. aborting.
Illegal instruction
```

**Comment by hintofbasil** [comment]
I encountered a very similar issue.

I unfortunately was only able to get the output from the console [vault_log.txt](https://github.com/maidsafe/safe_vault/files/333705/vault_log.txt).

**Comment by Bluebird45** [comment]
More details: That happened while the seed vault was running last night's build from the master branch. The seed vault has been running that build for 5 hours now and I haven't seen that error on my client vaults.

**Comment by Bluebird45** [comment]
I saw that error just now at the exact moment that I killed another vault running on the same host:

```
thread 'Crust PeerId(5947..) event loop' panicked at 'Logic Error', ../src/libcore/option.rs:700
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'Node thread' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', ../src/libcore/result.rs:746
thread 'Node thread' panicked at '

 ==============================
| Result evaluated to Err: Any |
 ==============================

', /home/travis/.cargo/registry/src/github.com-88ac128001ac3a9a/maidsafe_utilities-0.6.0/src/thread.rs:37
stack backtrace:
   1:           0x77c5a0 - std::sys::backtrace::tracing::imp::write::h4c73fcd3363076f5
   2:           0x78022b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h0422dbb3077e6747
   3:           0x77feb3 - std::panicking::default_hook::haac48fa641db8fa2
   4:           0x76b5bf - std::sys_common::unwind::begin_unwind_inner::h39d40f52add53ef7
   5:           0x76c858 - std::sys_common::unwind::begin_unwind_fmt::h64c0ff793199cc1b
   6:           0x5d5f7f - _<thread..RaiiThreadJoiner as std..ops..Drop>::drop::h2f72648cf85a5235
   7:           0x4ad812 - crust..Service::drop_contents.23336::hf90ae88ccf4b1bf8
   8:           0x4ad1ce - core..Core::drop.23331::hf9130c13607d9797
   9:           0x560225 - std::sys_common::unwind::try::try_fn::ha116764aacfa08c1
  10:           0x77b77b - __rust_try
  11:           0x77b70d - std::sys_common::unwind::inner_try::h9eebd8dc83f388a6
  12:           0x5603ea - _<F as std..boxed..FnBox<A>>::call_box::had2bfc8e3c719a1b
  13:           0x77ef34 - std::sys::thread::Thread::new::thread_start::h471ad90789353b5b
thread panicked while panicking. aborting.
Illegal instruction
```

**Comment by lionel1704** [comment]
A newly architectured vault has been released. Hence, I'm closing this issue.
